### ISSUE TITLE
Time spending on training

### ISSUE THREAD

**Issue by Bang2hen1iu** [buggyyang/RVD#1]
Hi, there. I'm interested in how many TITAN RTX are used during the training phase and how long will it takes for completing 1 million steps.

**Comment by buggyyang** [comment]
Training a model like this could be demanding. We usually use 4 rtx titan to train a 128 resolution model (each with batch size=1) it took around 5 days if my memory is correct. If you need, please send me an email (see our arxiv paper for my email address), I can share you a trained model for Cityscape dataset.

**Comment by JinkaiZheng** [comment]
Hi @buggyyang , thanks for your wonderful work! 
I am also interested in how long will it takes for testing, i.e., sampling a video. Could you tell me, please?

**Comment by buggyyang** [comment]
@JinkaiZheng . It depends on the video resolution and the number of denoising steps you choose. I didn't estimate the exact time, but I have to admit that sampling a video is slower than other generative models. Actually, if you do want to accelerate the sampling speed, you can try some 3D convolution architectures to sample multiple frames each time like [this google's work](https://video-diffusion.github.io/).

**Comment by JinkaiZheng** [comment]
Thanks a lot for your kind response!
