### ISSUE TITLE
Test_config

### ISSUE THREAD

**Issue by diaodeyi** [buggyyang/RVD#2]
hi, thanks for your great work, can you provide the test_config?

**Comment by JunyaoHu** [comment]
+1, nice work, but your `config_test.py` and other files have been ignored when pushing your git bacause i find your `.gitignore` file added them, and i really hope you upload them early, thanks!

**Comment by buggyyang** [comment]
@JunyaoHu @diaodeyi Sorry for the late reply, I just upload the config_test.py file, which is actually similar to config.py. For the rest files in .gitignore, they are basically some misc files unrelated to the experiment.
