### ISSUE TITLE
the batchsize in the calculation of FVD 

### ISSUE THREAD

**Issue by JunyaoHu** [buggyyang/RVD#3]
your work on diffusion for video prediction is very constructive for me, but i see your test batchsize is 10

https://github.com/buggyyang/RVD/blob/309fbe0d4faeb84f3cfece15d5e85a54f71ba3cb/config_test.py#L4

it will be better to set batchsize = 256 for more fair contrast, your data in the paper is too high because test batchsize is too small i think.

and i use your pretrained model to calculate the modified fvd on 256 video clips, 

![image](https://user-images.githubusercontent.com/67564714/227202977-f3f74abc-63fe-4cd6-ae06-5dfd0857f720.png)

some reference:

FVD: A NEW METRIC FOR VIDEO GENERATION
![image](https://user-images.githubusercontent.com/67564714/227201596-fa0b6c06-d394-4b34-bb06-4e03b9cd2141.png)

Masked Conditional Video Diffusion for Prediction, Generation, and Interpolation
![image](https://user-images.githubusercontent.com/67564714/227201658-002144a7-cf52-4dce-8dcb-a3d1979966b4.png)

**Comment by buggyyang** [comment]
@JunyaoHu You probably misunderstand something, we can simply split the test samples into multiple smaller batches, we can save some GPU memory with smaller batchsize (but you may need more time to iterate the test samples). And FVD score depends on the test samples you select, the backbone model you used, even which layer of the feature maps you extract. In some cases even the hardware/software platform will also influence the numerical results, so different people may have different scores with large variance. For example, this paper also report high FVD on KTH dataset: [Clockwork Variational Autoencoders](https://arxiv.org/pdf/2102.09532.pdf). The safest way to report FVD score is to run your model and baseline model on your own.

**Comment by JunyaoHu** [comment]
ok... thanks for your patient answer, so your FVD is based on a batch of 10 test videos, and then you take the average many times through iteration?

**Comment by buggyyang** [comment]
@JunyaoHu We use 50 test videos (as autoregressive diffusion model is slow, using 256 test samples for high-res test samples is time-consuming). We use batchsize=10 to generate videos and use the whole 50 videos for FVD evaluation. There is no "averaging".

**Comment by JunyaoHu** [comment]
ok, thanks a lot!
